### ISSUE TITLE
No hot reload

### ISSUE THREAD

**Issue by alexanderisora** [msaracevic/react-embed-gist#1]
Guten tag, Miroslav! Thanks for the package. Works like a charm!

Issue: when I change the `gist` attr value, the component does not react on it. 
Expected behavior: the component loads new snippet.

Any chances to get this functionality? Thanks!

**Comment by msaracevic** [comment]
Hmmm, definitely it should work as you expect it. I am not able to take a look at this moment, but I will try to fix it in next 48 hours

**Comment by msaracevic** [comment]
https://github.com/msaracevic/react-embed-gist/pull/2/files

**Comment by msaracevic** [comment]
New PR should fix all the issues of updating when `gist` param gets changed. It will also fix all the other params as well.

**Comment by alexanderisora** [comment]
Hey Miroslav. Thanks for the super-hero speed reaction! :)
I have updated the component to the latest version (1.0.9) but it still does not hot reload.

Should I provide more info?

**Comment by msaracevic** [comment]
Hi, can you please double check in your `node_modules/react-embed-gist/package.json` that it indeed does say `"version": "1.0.9"` so that we can eliminate possibility that for some reason older version was installed

With `1.0.9` I just tested this minimal code snippet, the gist gets updated as expected

```
import React, {Component} from 'react';
import ReactEmbedGist from 'react-embed-gist'

export default class EmbeddedGist extends Component {
  constructor(props) {
    super(props);
    this.state = { gist: 'msaracevic/7a315f610c11d39aeea55061d3b9bf05' }
  }

  componentDidMount() {
    setTimeout(() => this.setState({
      gist: 'msaracevic/5d757e2fc72482a9a4a439969500c2eb'
    }), 3000);
  }

  render() {
    return (<ReactEmbedGist gist={this.state.gist}/>);
  }
}
```

If you are still having issues with `1.0.9` please compare with the above snippet to see if you are doing similar thing. If you still can't get it to work as expected please either put here snippet of code which is failing or link to code _(github, jsfiddle, etc...)_

**Comment by alexanderisora** [comment]
Hey! Yes, it is v1.0.9: https://take.ms/zNpjX

```

import React, {Component} from "react";
import ReactEmbedGist from 'react-embed-gist';

class Code01 extends Component<Props>{
    generator = new generateContentDataObject();

    constructor(props) {
        super(props);
        this.state = { gist: 'msaracevic/7a315f610c11d39aeea55061d3b9bf05' }
    }
    componentDidMount(): void {
        setTimeout(() => this.setState({
            gist: 'msaracevic/5d757e2fc72482a9a4a439969500c2eb'
        }), 10000);
    }

    componentWillMount(): void {
    }

    render(){
        console.log('this.state:', this.state);

        return (
            <section>
                <div className="code-01">
                    <div className="code-01__container container container--mid">
                        <ReactEmbedGist
                            gist={this.state['gist']}
                            // wrapperClass="gist__bash"
                            loadingClass="loading__screen"
                            titleClass="gist__title"
                            // file=".bash_profile.sh"
                        />

                    </div>
                </div>
            </section>
        )
    }
}

export default Code01;

```


The state is changed (I can see that from the `console.log`). But the gist is not reloaded.

**Comment by msaracevic** [comment]
Unfortunately I can't replicate your issue. Copy paste of this code worked on my local machine. Are you sure that something else is not killing the javascript execution in rest of your code or that there are no network timeouts?

https://youtu.be/ylIWrY_rWSU
I will delete this video in next 24 hours, just show me literally doing copy paste and seeing it work

**Comment by alexanderisora** [comment]
Thanks for the video! That is strange, but it started to work by itself, without any code changes. So it works now. Thanks and sorry for wasting your time 💛 

However, a new problem appeared 😞 
If the `gist` param is incorrect, there is an uncatched error appeared. Just try to pass an empty string or 'blahblah' and the app will crash.

**Comment by msaracevic** [comment]
I am aware of that missing error handler, just didn't really though that this module was used that much or that people had issues with passing wrong params.

I will look it over tomorrow and add it

**Comment by alexanderisora** [comment]
In case you are interested in my use case: I'm making a website builder for geeks. Geeks often need to present their code, so I've added a special Code component which displays a GitHub Gist code into a web page. 
Users put a Gist URL and your package displays the Gist for them: https://monosnap.com/file/lfIzIa3aEbhacKeRIs7lRS6eRnqCzZ

I will try to add some protection on my side too. But if you come with a good error handling I will update the package instantly 😸

**Comment by msaracevic** [comment]
There is basic error handler which is blanket catching all errors.

If the format is invalid, it will say so in start and not even try to load gist.

Any other error will be caught and generic message will be displayed. However figuring out what really went wrong is not that straightforward. So for now just simple error catching is available in https://github.com/msaracevic/react-embed-gist/pull/4

**Comment by alexanderisora** [comment]
You made my day @msaracevic. Thanks! 😁 

Do you want a free 1 year subscription of the Maker plan for my [landing page builder](https://unicornplatform.com) as a gift?

**Comment by msaracevic** [comment]
No worries, glad it helps you.

About subscription, thanks for the offer, but at the moment I am not working on any projects which could make use of it.
