### ISSUE TITLE
Type annotations errors

### ISSUE THREAD

**Issue by gap689** [msaracevic/react-embed-gist#13]
I'm using typescript and getting the following error:
Type '{ gist: "gap689/c573a9304f0efbea811e55476bac64d2"; loadingFallback: Element; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'loadingFallback' does not exist on type 'IntrinsicAttributes & Props'.
  
This when using
<ReactEmbedGist
    gist="..."
    loadingFallback={<SiGooglecolab/>}
/>
where <SiGooglecolab/> is a react-icon.

**Comment by msaracevic** [comment]
I don't actually know how to include types into libraries. I will look into adding into the library directly.

I am assuming you installed `@types/react-embed-gist` which is maintained by somebody else, the error is most likely coming from [there](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-embed-gist/index.d.ts).

I will try over the weekend to either create PR there to fix it or I will look into including types into the lib itself. Or you can propose PR's as well.

**Comment by msaracevic** [comment]
Added types directly to this repo, should work now as long as you update to `1.0.22`
