### ISSUE TITLE
Server Error ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by MaximFedarau** [msaracevic/react-embed-gist#9]
When I try to deploy my Next.js app to Vercel I get an error above.
There is code snippet:
`<ReactEmbedGist gist={fastData}/>`, where var fastData contains gist.

**Comment by msaracevic** [comment]
Just to confirm, `{fastData}` is `typeof string`?

**Comment by msaracevic** [comment]
Some more information would be needed, what is the minimum required code for me to reproduce this error? 

It's super vague currently and considering the popularity of `next.js`, I would assume it would come up earlier as well as an issue if it was `next.js` specific.

**Comment by MaximFedarau** [comment]
> Just to confirm, `{fastData}` is `typeof string`?

Yeah, certainly.

**Comment by MaximFedarau** [comment]
> Also, some more information would be needed, what is the minimum required code for me to reproduce this error?
> 
> It's super vague currently and considering the popularity of `next.js`, I would assume it would come up earlier as well as an issue if it was `next.js` specific.

https://github.com/MaximFedarau/Guess-Coding-Language-Game/blob/testing-fast-gist/pages/index.js <- link to file

**Comment by msaracevic** [comment]
I've just cloned your master, followed by `npm install`, `npm install react-embed-gist`, `npm run dev`

I've added 

```      
<ReactEmbedGist
  gist="msaracevic/5d757e2fc72482a9a4a439969500c2eb"
  wrapperClass="gist__bash"
  loadingClass="loading__screen"
  titleClass="gist__title"
  errorClass="gist__error"
  contentClass="gist__content"
  file=".bash_profile.sh"
/>
 ```
 and it renders correctly, no issues

![image](https://user-images.githubusercontent.com/5228983/156848075-714dac6c-6e62-4e87-a8e6-944681462e82.png)

Could you provide me with a link to a gist that you are actually trying to render?

**Comment by MaximFedarau** [comment]
One moment, please. I wokr with GitHub API and random generate gists.

**Comment by msaracevic** [comment]
https://github.com/nrwl/nx/issues/5063#issuecomment-802851556 this seems to fix the issue

Add `import 'regenerator-runtime/runtime';` to `_app.js`

**Comment by MaximFedarau** [comment]
Thank you very much. It is finally working!!!!
